env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:import/recommended'
  - airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
