env:
  browser: true
  es2021: true
extends: extends:
    - 'eslint:recommended'
    - 'plugin:jest/recommended'
    - 'plugin:import/recommended'
    - airbnb-base

overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
